cache:
  paths:
    - openstack-lib/.venv

openstack-lint:
  stage: test
  cache: []
  only:
    - branches
  before_script:
    - pip install ruff
  script:
    - cd openstack-lib/
    - ruff check

openstack-test:
  stage: test
  only:
    - branches
  script:
    - cd openstack-lib/
    - poetry install
    - poetry run tox

openstack-build:
  stage: test
  only:
    - branches
  script:
    - cd openstack-lib/
    - poetry build

openstack-upload:
  stage: upload
  only:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[release\]/
  script:
    - cd openstack-lib/
    - poetry publish --build --repository cyberrangecz
